In [1]:
import numpy as np
import random
from time import sleep

def create_board():
    return np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])

def possibilities(board):
    l = []
    for i in range(len(board)):
        for j in range(len(board[i])):
            if board[i, j] == 0:
                l.append((i, j))
    return l

def random_place(board, player):
    selection = possibilities(board)
    current_loc = random.choice(selection)
    board[current_loc] = player
    return board

def row_win(board, player):
    for x in range(len(board)):
        win = True
        for y in range(len(board)):
            if board[x, y] != player:
                win = False
                break
        if win:
            return True
    return False

def diag_win(board, player):
    win = True
    for x in range(len(board)):
        if board[x, x] != player:
            win = False
            break
    if win:
        return True

    win = True
    for x in range(len(board)):
        if board[x, len(board) - 1 - x] != player:
            win = False
            break
    return win

def evaluate(board):
    winner = 0
    for player in [1, 2]:
        if row_win(board, player) or diag_win(board, player):
            winner = player
            break
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner

def play_game():
    board, winner, counter = create_board(), 0, 1
    print("Initial Board:")
    print(board)
    sleep(2)

    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print("Board after move " + str(counter) + ":")
            print(board)
            sleep(2)

            winner = evaluate(board)
            counter += 1

            if winner != 0:
                break

    if winner == -1:
        print("It's a tie!")
    else:
        print("Player " + str(winner) + " wins!")

# Example usage:
print("Result: Tic-tac-toe game implemented successfully.")
play_game()

Result: Tic-tac-toe game implemented successfully.
Initial Board:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after move 1:
[[0 0 0]
 [0 0 1]
 [0 0 0]]
Board after move 2:
[[0 0 0]
 [0 2 1]
 [0 0 0]]
Board after move 3:
[[0 0 0]
 [1 2 1]
 [0 0 0]]
Board after move 4:
[[0 0 0]
 [1 2 1]
 [2 0 0]]
Board after move 5:
[[1 0 0]
 [1 2 1]
 [2 0 0]]
Board after move 6:
[[1 0 2]
 [1 2 1]
 [2 0 0]]
Player 2 wins!
